// ignore_for_file: constant_identifier_names, non_constant_identifier_names
const AUTH_BASE_BASE_URL = "https://authqa.bosapps.net/api/v1/";
const API_BASE_URL = "API_BASE_URL";
const USER_INFO_BOX = 'userInfo';
const LOGIN_BOX = 'LOGIN_BOX';
const OPERATOR_TYPE = 'OPERATOR_TYPE';
const FIRST_NAME = 'FIRST_NAME';
const LAST_NAME = 'LAST_NAME';
const USER_ID = 'USER_ID';
const BU = 'BU';
const BRANCH = 'BRANCH';
const VEHICLEID = 'VEHICLEID';
const PERMISSION = "PERMISSION";
const ORGANIZATION_BOX = "ORGANIZATION_BOX";
const ORGANIZATION_VALUE = "ORGANIZATION_VALUE";
const ORGANIZATION_KEY = "ORGANIZATION_KEY";
